import Image from "next/image";
import MSCNavbar from "./_components/navbar";
import { api } from "@/trpc/server";
import { Category } from "@prisma/client";
import { RocketIcon } from "lucide-react";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function Home() {
  const categories = (await api.category.findMany.query({
    length: 4,
  })) as Partial<Category>[];

  if (categories.length < 4) {
    for (let i = categories.length; i < 4; i++) {
      categories.push({
        cuid: "" + Math.random(),
        name: "TBC",
      });
    }
  }

  console.log(categories);

  return (
    <div className="min-h-[100dvh] w-full">
      <div className="relative flex min-h-screen items-center justify-center bg-hero bg-cover bg-center">
        <Image
          src={"/stats.png"}
          alt="Stats"
          width={750}
          height={1000}
          className="absolute w-full max-w-lg object-contain"
        />
        <h1 className="relative font-sansation-bold text-3xl sm:text-7xl">
          <span className="opacity-0">
            SINGAPORE MEMORY <br />
            SPORTS
          </span>
          <span className="absolute inset-0 translate-x-[4px] text-center text-[#7089DF]">
            SINGAPORE MEMORY <br />
            SPORTS
          </span>
          <span className="absolute inset-0 text-center text-white">
            SINGAPORE MEMORY <br />
            SPORTS
          </span>
        </h1>
      </div>
      <div className="p-8">
        <div className="flex flex-col border-8 border-[#A19797] bg-board-texture bg-cover py-12 shadow-lg sm:flex-row">
          <div className="relative m-8 flex-1">
            <Image
              className="-rotate-2 shadow-md"
              src={"/board/msc.png"}
              alt="MSC Training Session"
              height={585}
              width={760}
            />
            <Image
              src={"/board/clip.png"}
              height={100}
              width={100}
              alt="clip"
              className="absolute -top-10 left-1/2 w-[75px] -translate-x-1/2 -rotate-2 sm:-top-12 sm:w-[100px]"
            />
          </div>
          <div className="relative m-8 ml-4 flex flex-1 rotate-3 flex-col items-center space-y-12 bg-primary-blue p-4 font-sansation text-white shadow-md">
            <Image
              className="absolute -left-8 -top-8"
              src={"/board/tape.png"}
              height={100}
              width={100}
              alt="clip"
            />
            <Image
              className="absolute -bottom-8 -right-8"
              src={"/board/tape.png"}
              height={100}
              width={100}
              alt="clip"
            />
            <h1 className=" my-4 w-max bg-white px-6 py-2 text-center font-sansation-bold text-black sm:text-xl">
              ABOUT SINGAPORE
              <br />
              MEMORY SPORTS
            </h1>
            <p className="px-4 text-justify sm:px-8 sm:text-lg">
              Singapore Polytechnic&#39;s Memory Sports CCA is a vibrant
              community within Singapore Polytechnic dedicated to pushing the
              boundaries of memory enhancement. <br />
              <br /> Through engaging activities, workshops, and competitions,
              members are empowered to unlock their cognitive potential using
              mnemonic techniques and memory challenges. <br />
              <br />
              The CCA fosters collaboration, camaraderie, and lasting
              friendships while representing the polytechnic in regional and
              international memory competitions, showcasing dedication, skill,
              and determination on a global stage.
            </p>
          </div>
        </div>
      </div>
      <div className="flex p-8 bg-gray-200 space-x-8">
        <div className="flex-1 bg-white rounded-lg p-4">
          {categories.map((c) => {
            if (c.name === "TBC") {
              return (
                <div key={c.cuid}>
                  <RocketIcon size={48} />
                  <h1 className="text-center">COMING SOON</h1>
                </div>
              );
            }

            return <div key={c.cuid}>{c.name}</div>;
          })}
        </div>
        <div className="flex-1 bg-white rounded-lg p-4"></div>
      </div>
    </div>
  );
}
